name: Rust

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: riscv64gc-unknown-none-elf
        components: clippy
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - name: Install Dependencies
      run: sudo apt-get install build-essential binutils-riscv64-linux-gnu
    - name: Build
      run: make BINUTILS_TOOLCHAIN=riscv64-linux-gnu
    - name: Run tests
      run: cargo test --verbose

